SAMPLES: 
 - sampleA
CHROMOSOMES: 
 - chr1
REPLACEMENT_STATISTICS_FILENAME: "results/replacement_statistics.tsv"
DOWNLOAD_VIA_SCP: False
DOWNLOAD_CMD: 
 - "scp HOST:PATH_PHASED/{wildcards.sample}.{wildcards.chr}.vcf.gz {output.phased}; "
 - "scp HOST:PATH_UNPHASED/{wildcards.sample}.{wildcards.chr}.vcf.gz {output.unphased}; "